services:
    prometheus:
      image: prom/prometheus:latest
      ports:
        - "9090:9090"
      volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      networks:
        - monitoring
      extra_hosts:
        - 'host.docker.internal:host-gateway'

    loki:
      image: grafana/loki:latest
      ports:
        - "3100:3100"
      volumes:
        - ./loki/loki-config.yml:/etc/loki/config.yml
        - loki_data:/loki
      networks:
        - monitoring

    promtail:
      image: grafana/promtail:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./promtail/promtail-config.yml:/etc/promtail/config.yml
        - /var/lib/docker/containers:/var/lib/docker/containers:ro
      depends_on:
        - loki
      networks:
        - monitoring

    grafana:
      image: grafana/grafana:latest
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin
        - GF_USERS_ALLOW_SIGN_UP=false
      volumes:
        - grafana_data:/var/lib/grafana
        - ./grafana/provisioning:/etc/grafana/provisioning
        - ./grafana/dashboards:/var/lib/grafana/dashboards
      depends_on:
        - prometheus
        - loki
      networks:
        - monitoring
          
networks:
    monitoring:
volumes:
    loki_data:
    grafana_data: