name: ci
on:
  push: { branches: [main, dev] }
  pull_request: { branches: [main, dev] }
  workflow_dispatch:

permissions:
  contents: read
  packages: write 

jobs:
  pipeline:
    uses: Path-Of-Execution-Team/FlashCards/.github/workflows/reusable-build-deploy.yml@main
    with:
      lang: java
      image_name: ghcr.io/path-of-execution-team/flashcardshostedservices
      container_name: hosted
      deployment_dev: hosted
      deployment_prod: hosted
      namespace_dev: flashcards-dev
      namespace_prod: flashcards
      build_context: .
      dockerfile: ./Dockerfile
      test_command: "mvn -B -ntp test"
      deploy_mode: direct
      platform: linux/arm64
    secrets: inherit
